// services/nginxPreviewService.js
//
// Manages per-workspace nginx config files so each running dev server
// gets its own subdomain origin — no path-prefix URL rewriting needed.
//
// How it works:
//   1. When a port is detected (e.g. Vite on 5173), we write an nginx
//      server block that routes `workspace-{id}-5173.PREVIEW_DOMAIN`
//      → container bridge IP:5173.
//   2. `nginx -s reload` picks up the new config instantly.
//   3. The frontend uses that subdomain as the iframe src — the browser
//      treats it as its own origin, so absolute paths like /@vite/client
//      resolve correctly without any URL rewriting.
//   4. WebSocket (Vite HMR) works via nginx's built-in upgrade support.
//
// Environment variables (set in .env):
//   NGINX_PREVIEW=true               enable this service
//   NGINX_PREVIEW_CONF_DIR           where to write per-workspace .conf files
//                                    default: /etc/nginx/conf.d/preview
//   NGINX_PREVIEW_PORT               port nginx listens on for previews
//                                    default: 8080
//   NGINX_RELOAD_CMD                 command to reload nginx
//                                    default: nginx -s reload
//   NGINX_PREVIEW_SSL_CERT           path to fullchain.pem (enables HTTPS)
//   NGINX_PREVIEW_SSL_KEY            path to privkey.pem   (enables HTTPS)
//   PREVIEW_DOMAIN                   subdomain used for preview URLs
//                                    local:  preview.lvh.me  (resolves to 127.0.0.1)
//                                    prod:   preview.yourapp.com (wildcard DNS → server)

const fs = require('fs').promises;
const path = require('path');
const { exec } = require('child_process');
const { promisify } = require('util');

const execAsync = promisify(exec);

const ENABLED      = process.env.NGINX_PREVIEW === 'true';
const CONF_DIR     = process.env.NGINX_PREVIEW_CONF_DIR || '/etc/nginx/conf.d/preview';
const NGINX_PORT   = process.env.NGINX_PREVIEW_PORT     || '8080';
const RELOAD_CMD   = process.env.NGINX_RELOAD_CMD       || 'nginx -s reload';
const DOMAIN       = process.env.PREVIEW_DOMAIN         || 'preview.lvh.me';
const SSL_CERT     = process.env.NGINX_PREVIEW_SSL_CERT || '';
const SSL_KEY      = process.env.NGINX_PREVIEW_SSL_KEY  || '';
const USE_SSL      = !!(SSL_CERT && SSL_KEY);

exports.ENABLED = ENABLED;

// Build the public preview URL for a given container + container-side port
exports.getPreviewUrl = (containerName, port) => {
  if (!ENABLED) return null;
  const scheme = USE_SSL ? 'https' : 'http';
  const portSuffix = (NGINX_PORT === '80' || NGINX_PORT === '443') ? '' : `:${NGINX_PORT}`;
  return `${scheme}://${containerName}-${port}.${DOMAIN}${portSuffix}`;
};

// Write an nginx server block and reload nginx
exports.addPreviewRoute = async (containerName, containerIP, port) => {
  if (!ENABLED) return;

  // nginx upstream names cannot contain hyphens
  const upstream = `${containerName}_${port}`.replace(/-/g, '_');
  const serverName = `${containerName}-${port}.${DOMAIN}`;

  const sslDirectives = USE_SSL
    ? `\n    ssl_certificate     ${SSL_CERT};\n    ssl_certificate_key ${SSL_KEY};\n    ssl_protocols       TLSv1.2 TLSv1.3;\n    ssl_ciphers         HIGH:!aNULL:!MD5;`
    : '';

  const conf = `# Auto-generated by Code Guru preview service — do not edit manually
upstream ${upstream} {
    server ${containerIP}:${port};
    keepalive 8;
}
server {
    listen ${NGINX_PORT}${USE_SSL ? ' ssl' : ''};
    server_name ${serverName};${sslDirectives}

    location / {
        proxy_pass         http://${upstream};
        proxy_http_version 1.1;

        # WebSocket / Vite HMR
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";

        proxy_set_header   Host       $http_host;
        proxy_set_header   X-Real-IP  $remote_addr;

        # Disable buffering so the browser gets streamed responses immediately
        proxy_buffering    off;
        proxy_cache        off;
    }
}
`;

  try {
    await fs.mkdir(CONF_DIR, { recursive: true });
    await fs.writeFile(path.join(CONF_DIR, `${containerName}-${port}.conf`), conf);
    await execAsync(RELOAD_CMD);
    console.log(`[nginx] route added: ${serverName} → ${containerIP}:${port}`);
    return true;
  } catch (err) {
    console.error('[nginx] addPreviewRoute failed:', err.message);
    // Clean up the conf file so stale configs don't accumulate
    fs.unlink(path.join(CONF_DIR, `${containerName}-${port}.conf`)).catch(() => {});
    return false;
  }
};

// Remove all nginx routes for a container (called on disconnect / TTL cleanup)
exports.removePreviewRoutes = async (containerName) => {
  if (!ENABLED) return;

  try {
    const files = await fs.readdir(CONF_DIR).catch(() => []);
    const mine  = files.filter((f) => f.startsWith(`${containerName}-`) && f.endsWith('.conf'));

    if (!mine.length) return;

    await Promise.all(mine.map((f) => fs.unlink(path.join(CONF_DIR, f)).catch(() => {})));
    await execAsync(RELOAD_CMD).catch(() => {});
    console.log(`[nginx] removed ${mine.length} route(s) for ${containerName}`);
  } catch (err) {
    console.error('[nginx] removePreviewRoutes failed:', err.message);
  }
};
